Support the openvino async
Adlik/Adlik pull request #410
Opened 2021-02-08 02:07 UTC by wangzhenyu32

Closes #370

2021-02-08 07:38 UTC, amadeus-zte commented on adlik_serving/runtime/openvino/model/ir_model.cc
> +  if (currentBatchSize != config.max_batch_size()) {
Is it proper?

2021-02-09 01:56 UTC, shiyingjin requested changes

2021-02-09 01:56 UTC, shiyingjin commented on adlik_serving/runtime/openvino/model/ir_model.cc
> +    ExecutableNetwork executableNetwork = core.LoadNetwork(network, "CPU");
Can ExecutableNetwork be shared by multiple infer_request?

2021-02-09 01:56 UTC, shiyingjin commented on adlik_serving/runtime/openvino/model/ir_model.cc
> +  if (currentBatchSize != config.max_batch_size()) {
Yes

2021-02-09 02:41 UTC, shiyingjin approved these changes

2021-02-09 07:16 UTC, amadeus-zte commented
bors r+

2021-02-18 03:11 UTC, amadeus-zte commented
bors retry

2021-02-19 09:13 UTC, amadeus-zte commented
bors r+

2021-02-23 11:14 UTC, amadeus-zte commented
bors r+

2021-02-23 11:41 UTC, closed without merging