Fixed bugs for version 0.4.0.
Adlik/Adlik pull request #591
Opened 2022-07-26 09:14 UTC by nengyinyibeiwu

2022-07-26 11:48 UTC, shiyingjin requested changes
In  README.md  “git clone https://github.com/ZTE/Adlik.git”  should be " https://github.com/Adlik/Adlik.git"

2022-07-26 11:48 UTC, shiyingjin commented on README.md
> +model, and TensorRT model. The name and label of compiler mirror is shown below, and the first half of label
"is shown" should be "are shown"

2022-07-26 11:48 UTC, shiyingjin commented on docker-images/dockerfiles/serving-tensorrt.dockerfile
> +         --jobs=3
Why "--jobs=3"?

2022-07-27 01:25 UTC, NaNAGISaSA requested changes

2022-07-27 01:25 UTC, NaNAGISaSA commented on docker-images/dockerfiles/model-compiler.dockerfile
> +		gnupg curl software-properties-common && \
Better to merge these two lines:
`
	apt-get install --no-install-recommends -y \
		gnupg curl software-properties-common && \
`
into one line.

2022-07-27 01:25 UTC, NaNAGISaSA commented on docker-images/dockerfiles/serving-tensorrt.dockerfile
> +    apt-get install --no-install-recommends -y \
Better to merge these two lines:
`
	apt-get install --no-install-recommends -y \
		gnupg curl software-properties-common && \
`
into one line.

2022-07-27 01:50 UTC, NaNAGISaSA commented
The pull request title should be modified too, describing what is really done in this PR.

2022-07-28 01:03 UTC, shiyingjin requested changes

2022-07-28 01:03 UTC, shiyingjin commented on README.md
> +   registry.cn-beijing.aliyuncs.com/adlik/model-compiler:v0.4.0_trt7.1.3.4_cuda11.0 bash
Why tensorrt downgrade to 7.1.3.4?

2022-07-28 01:03 UTC, shiyingjin commented on README.md
> +registry.cn-beijing.aliyuncs.com/adlik/model-compiler:v0.4.0_trt7.1.3.4_cuda11.0
Why tensorrt downgrade to 7.1.3.4?

2022-07-29 06:37 UTC, shiyingjin requested changes

2022-07-29 06:37 UTC, shiyingjin commented on docker-images/build.py
> +# _TENSORRT_VERSION = '7.1.3.4'
Remove the commented code

2022-07-29 08:51 UTC, shiyingjin approved these changes

2022-07-29 08:54 UTC, shiyingjin requested changes

2022-07-29 08:54 UTC, shiyingjin commented on docker-images/build.py
>  # _CUDA_VERSION = '10.2'
Remove the commented code  "# _CUDA_VERSION = '10.2'"

2022-08-01 00:57 UTC, shiyingjin approved these changes

2022-08-01 01:14 UTC, NaNAGISaSA approved these changes

2022-08-01 01:15 UTC, NaNAGISaSA commented
bors r+

2022-08-01 01:37 UTC, closed without merging