Upgrade openvino of compiler to version 2022.1.0
Adlik/Adlik pull request #592
Opened 2022-07-27 08:57 UTC by 982118809

Signed-off-by: 王佳越 10335419 <wang.jiayue@zte.com.cn>

2022-08-08 02:30 UTC, shiyingjin requested changes

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/src/model_compiler/compilers/saved_model_file_to_openvino_model.py
> +    # if not config.enable_nhwc_to_nchw:
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/src/model_compiler/compilers/saved_model_to_openvino_model.py
> +    #     params['disable_nhwc_to_nchw'] = None
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/src/model_compiler/compilers/tf_frozen_graph_model_file_to_openvino_model.py
> +    #     params['disable_nhwc_to_nchw'] = None
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/src/model_compiler/compilers/tf_model_file_to_openvino_model.py
> +    #     params['disable_nhwc_to_nchw'] = None
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/src/model_compiler/openvino_util.py
> +        # enable_nhwc_to_nchw = bool(int(temp_enable_nhwc_to_nchw)) if temp_enable_nhwc_to_nchw else None
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/tests/model_compiler/compilers/test_saved_model_file_to_openvino_model.py
> +    #                          [ModelOutput(name='z', data_type=tf.float32.as_datatype_enum, dims=[4, 2, 3])])
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/tests/model_compiler/compilers/test_saved_model_to_openvino_model.py
> +    #                      [ModelOutput(name='z', data_type=tf.float32.as_datatype_enum, dims=[4, 2, 3])])
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/tests/model_compiler/compilers/test_tf_forzen_graph_file_to_openvino_model.py
> +    #                          [ModelOutput(name='z', data_type=tf.float32.as_datatype_enum, dims=[4, 2, 3])])
Remove the commented code

2022-08-08 02:30 UTC, shiyingjin commented on model_compiler/tests/model_compiler/compilers/test_tf_model_file_to_openvino_model.py
> +    #                          [ModelOutput(name='z', data_type=tf.float32.as_datatype_enum, dims=[4, 2, 3])])
Remove the commented code

2022-08-08 06:08 UTC, NaNAGISaSA requested changes

2022-08-08 06:08 UTC, NaNAGISaSA commented on model_compiler/src/model_compiler/openvino_util.py
> +
remove blank line

2022-08-08 06:08 UTC, NaNAGISaSA commented on model_compiler/src/model_compiler/openvino_util.py
> +
remove blank line

2022-08-09 02:00 UTC, shiyingjin approved these changes

2022-08-09 02:18 UTC, NaNAGISaSA approved these changes

2022-08-09 02:18 UTC, NaNAGISaSA commented
bors r+

2022-08-09 02:36 UTC, closed without merging