Support enflame_runtime
Adlik/Adlik pull request #622
Opened 2022-11-07 03:16 UTC by shimei0203

Signed-off-by: Shi mei <shi.mei1@zte.com.cn>

2022-11-09 07:47 UTC, shiyingjin requested changes

2022-11-09 07:47 UTC, shiyingjin commented on ci/azure-pipelines/jobs/bazel-build-serving-enflame.yml
> +jobs:
How to prepare enflame dependencies?

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_util.h
> +bool ConvertDims(const std::vector<int>&, adlik::serving::DimsList&);
I think this function has been implemented in some place

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.h
> +#ifndef ADLIK_SERVING_RUNTIME_ENFLAME_MODEL_PADDLE_MODEL_H
Include guard: "......PADDLE_MODEL_H" ?

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +#include <dtu/factor/program.h>
Need this header file?

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +  TopsInference::topsInference_init();
I think these codes are implementation details, should put in Instance class.

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +      : name(name), config(config), engine(model), stream(stream), max_batch_size(config.max_batch_size()) {
1. Where is the input parameter "stream"?
2. The initializer list should be match in member declaration order

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +      : name(name), data_type(data_type), address(address) {
byte_1batch_size and byte_size have not been initialized

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    TopsInference::mem_alloc(&storage_on_device, inputs.back().byte_size);
The allocated memory is asigned to storage_on_device, but inputs.back().address is still nullptr.

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    void* output_on_device = outputs.back().address;
This same to above

2022-11-09 07:47 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +          void* storage_on_device = &(input.address) + offsetByteSize;
&(input.address)   wrong

2022-11-11 01:36 UTC, shiyingjin requested changes

2022-11-11 01:36 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.h
> +#include <TopsInference/TopsInferRuntime.h>
This header is no need

2022-11-14 09:22 UTC, shiyingjin requested changes

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    MY_RETURN_IF_ERROR_TF(init_buffer(inputs.back(), model_input.dims()));
这部分代码应该放在buffer内部

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    outputs.emplace_back(model_output.name(), model_output.data_type(), output_on_device);
这部分代码应该放在buffer内部

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +  TopsInference::IEngine* model;
这两个局部变量和类成员engine、stream是什么关系？

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +  void* inputs_[] = {storage_on_device};
局部变量和类成员同名

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    inputs_total_byte_size = inputs_total_byte_size + inputs.back().byte_size;
用 +=

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    inputs[i].address = storage_on_device + i * inputs[i].byte_size;
这里不对吧？

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    outputs[i].address = output_on_device + i * outputs[i].byte_size;
这里不对吧？

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    outputs_total_byte_size = outputs_total_byte_size + outputs.back().byte_size;
用 +=

2022-11-14 09:22 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +      (void**)inputs_, (void**)outputs_, TopsInference::BufferType::TIF_ENGINE_RSC_IN_DEVICE_OUT_DEVICE, stream);
这个用**是为了多输入还是别的原因？如果是为了多输入\多输出，这里的用法就不对了

2022-11-16 02:45 UTC, shiyingjin requested changes
enflame是支持多输入、多输出的，接口中已经体现了，重新修改

2022-11-16 02:45 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    TopsInference::topsInference_finish();
storage_on_device,output_on_device同样需要考虑释放

2022-11-21 06:29 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +    if (address != nullptr) {
这里不对，address不是分配的，只是指向了storage_on_device、output_on_device的某个位置

2022-11-21 06:29 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +  }
建议address放在buffer中申请和释放，instance中不负责

2022-11-22 12:36 UTC, shiyingjin requested changes

2022-11-22 12:36 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +  for (auto& input : inputs) {
shape中不含有batch size，这里不能修改shape

2022-11-22 12:36 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +          input.shape[0] = input.shape[0] + batchSize;
这里不能修改shape

2022-11-22 12:36 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +                                             input.buffer_on_device,
dst不对，应该加上offset

2022-11-22 12:36 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +  for (auto& input : inputs) {
这段代码（for循环）去掉吧

2022-11-22 12:36 UTC, shiyingjin commented on adlik_serving/runtime/enflame/model/enflame_model.cc
> +          if (!TopsInference::mem_copy_async(output.buffer_on_device,
这里源应该加上offset

2022-11-30 03:24 UTC, shiyingjin requested changes

2022-11-30 08:02 UTC, shiyingjin requested changes

2022-12-08 06:45 UTC, shiyingjin requested changes

2022-12-08 06:45 UTC, shiyingjin commented on adlik_serving/runtime/topsinference/model/topsinference_model.cc
> +  Buffer(Buffer&& buffer)
将move构造函数也delete吧

2022-12-08 06:45 UTC, shiyingjin commented on adlik_serving/runtime/topsinference/model/topsinference_model.cc
> +  Buffer& operator=(Buffer&& buffer) {
delete掉

2022-12-08 06:45 UTC, shiyingjin commented on adlik_serving/runtime/topsinference/model/topsinference_model.cc
> +  auto* handler = TopsInference::set_device(0, cluster_id, 6, nullptr);
弄清楚这个接口怎么用？{0,1,2,3,4,5和6都是写死的吗？

2022-12-08 06:45 UTC, shiyingjin commented on adlik_serving/runtime/topsinference/model/topsinference_model.cc
> +  TopsInference::synchronize_stream(stream);
synchronize_stream是放在splitOutputs之后吗？

2022-12-08 06:45 UTC, shiyingjin commented on model_compiler/setup.py
> +_TYPES_PROTO_URL = 'https://github.com/tensorflow/tensorflow/raw/v2.10.1/tensorflow/core/framework/types.proto'
为什么改这里？

2022-12-08 06:54 UTC, shimei0203 commented on model_compiler/setup.py
> +_TYPES_PROTO_URL = 'https://github.com/tensorflow/tensorflow/raw/v2.10.1/tensorflow/core/framework/types.proto'
这个地方是固定版本的时候忘记改的。

2022-12-15 06:47 UTC, shiyingjin requested changes

2022-12-16 08:05 UTC, shiyingjin commented
bors r+

2022-12-16 13:05 UTC, closed without merging