[Merged by Bors] - Add compiler script of torch model to torchscript model
Adlik/Adlik pull request #639
Opened 2022-12-08 06:48 UTC by xidianwym

Signed-off-by: Wang Yiming <wang.yiming6@zte.com.cn>

2022-12-08 07:24 UTC, shiyingjin requested changes
重新rebase代码

2022-12-09 00:58 UTC, NaNAGISaSA requested changes

2022-12-09 10:25 UTC, xidianwym commented on model_compiler/src/model_compiler/compilers/torch_model_file_to_torchscript_model.py
> +    temp_path = TemporaryDirectory()
利用TemporaryDirectory构建的临时目录，在执行完上下文之后，会自动删除，不需要增加显示的删除代码

2022-12-11 03:34 UTC, shiyingjin approved these changes

2022-12-12 00:39 UTC, NaNAGISaSA requested changes

2022-12-12 00:39 UTC, NaNAGISaSA commented on model_compiler/src/model_compiler/compilers/torch_model_file_to_torchscript_model.py
> +    temp_path = TemporaryDirectory()
see how to use the context manager: [link](https://docs.python.org/3/library/tempfile.html#examples)

2022-12-13 02:04 UTC, NaNAGISaSA requested changes

2022-12-13 02:04 UTC, NaNAGISaSA commented on model_compiler/src/model_compiler/models/data_type.py
> +            torch.bool: DataType.BOOL,
the reason for this change?

2022-12-13 02:04 UTC, NaNAGISaSA commented on model_compiler/tests/model_compiler/compilers/test_torch_model_file_to_onnx_model.py
> +                                           'data_type': torch.float,     # pylint: disable=no-member
I think json config and env are common configs, it should not be related to frameworks like torch, tf etc.

2022-12-15 02:53 UTC, shiyingjin commented
bors r+

2022-12-15 06:51 UTC, closed without merging