Bump paddle version to 2.4.0
Adlik/Adlik pull request #645
Opened 2023-01-06 08:09 UTC by xidianwym

Signed-off-by: Wang Yiming <wang.yiming6@zte.com.cn>

2023-01-13 06:24 UTC, shiyingjin requested changes

2023-01-13 06:24 UTC, shiyingjin commented on adlik_serving/add_deps.bzl
> +            "https://paddle-inference.oss-cn-beijing.aliyuncs.com/paddle_inference.zip",
这个地址是我们的云，还是paddle的？这个zip是源码包吗？版本是多少？

2023-01-13 08:32 UTC, xidianwym commented on adlik_serving/add_deps.bzl
> +            "https://paddle-inference.oss-cn-beijing.aliyuncs.com/paddle_inference.zip",
这个是我们自己的云，这个zip包中的代码是通过修改源代码中的protobuf版本之后编译得到的推理库，版本是2.4.0

2023-01-13 09:17 UTC, shiyingjin commented on adlik_serving/add_deps.bzl
> +            "https://paddle-inference.oss-cn-beijing.aliyuncs.com/paddle_inference.zip",
名字上和url改一下，表明这是一个编译产物和表明版本号

2023-01-13 09:30 UTC, xidianwym commented on adlik_serving/add_deps.bzl
> +            "https://paddle-inference.oss-cn-beijing.aliyuncs.com/paddle_inference.zip",
好的

2023-01-16 08:54 UTC, shiyingjin commented on README.md
> +   <https://github.com/Adlik/Adlik/releases/download/v0.3.0/adlik_serving_api-0.3.0-py2.py3-none-any.whl>) or [adlik
为什么加<>？

2023-01-16 08:54 UTC, shiyingjin commented on docker-images/README.md
> +   <https://github.com/Adlik/Adlik/releases/download/v0.3.0/adlik_serving_api-0.3.0-py2.py3-none-any.whl>) or [adlik
为什么加<>？

2023-01-16 08:57 UTC, xidianwym commented on docker-images/README.md
> +   <https://github.com/Adlik/Adlik/releases/download/v0.3.0/adlik_serving_api-0.3.0-py2.py3-none-any.whl>) or [adlik
因为不加<>，markdownlint会报错，错误为docker-images/README.md:120:4 MD034/no-bare-urls Bare URL used [Context: "[https://github.com/Adlik/Adlik..."]

2023-01-16 09:06 UTC, shiyingjin approved these changes

2023-01-16 12:04 UTC, closed without merging