Add topsinference example
Adlik/Adlik pull request #658
Opened 2023-03-02 11:15 UTC by shimei0203

2023-03-09 11:41 UTC, shiyingjin requested changes

2023-03-09 11:41 UTC, shiyingjin commented on examples/topsinference_model/train_model.py
> +# Copyright 2019 ZTE corporation. All Rights Reserved.
这个脚本有什么用？没用

2023-03-09 11:41 UTC, shiyingjin commented on examples/topsinference_model/resnet50_client_acc.py
> +# Copyright 2021 ZTE corporation. All Rights Reserved.
这个脚本和其他运行时的client有什么区别，如果没有区别就是重复代码，不需要

2023-03-09 11:54 UTC, shimei0203 commented on examples/topsinference_model/train_model.py
> +# Copyright 2019 ZTE corporation. All Rights Reserved.
好的，在readme里面提供获取链接，https://github.com/Adlik/Adlik/blob/d1b39507f5a6d37e31a2f09a870e726f116db1df/examples/topsinference_model/train_model.py，这里就不写了。

2023-03-09 12:27 UTC, shimei0203 commented on examples/topsinference_model/resnet50_client_acc.py
> +# Copyright 2021 ZTE corporation. All Rights Reserved.
与其他运行时client是不一样的。有必要保留。

2023-03-14 03:02 UTC, shiyingjin commented
bors r+

2023-03-14 03:02 UTC, shiyingjin approved these changes

2023-03-14 03:27 UTC, closed without merging